CREATE DATABASE Reservas Senai;
-- ---------------------------------------------------------------------------
USE Reservas Senai;
-- ---------------------------------------------------------------------------
-- Tabela Usuários

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(150) NOT NULL
);
-- ---------------------------------------------------------------------------

-- Tabela Salas

CREATE TABLE salas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    disponibilidade BOOLEAN NOT NULL DEFAULT TRUE
);
-- ---------------------------------------------------------------------------

-- Tabela Características

CREATE TABLE caracteristicas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL
);
-- ---------------------------------------------------------------------------

-- Relacionamento entra Tabelas Salas e Características 

CREATE TABLE sala_caracteristicas (
    sala_id INTEGER NOT NULL,
    caracteristicas_id INTEGER NOT NULL,
    PRIMARY KEY (sala_id, caracteristicas_id),
    FOREIGN KEY (sala_id)
        REFERENCES salas(id),
    FOREIGN KEY (caracteristicas_id)
        REFERENCES caracteristicas(id)
);
-- ---------------------------------------------------------------------------
