CREATE DATABASE Reservas Senai;
-- ---------------------------------------------------------------------------
USE Reservas Senai;
-- ---------------------------------------------------------------------------
-- Tabela Usuários

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(150) NOT NULL
);
-- ---------------------------------------------------------------------------

-- Tabela Salas

CREATE TABLE salas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    disponibilidade BOOLEAN NOT NULL DEFAULT TRUE
);
-- ---------------------------------------------------------------------------

-- Tabela Características

CREATE TABLE caracteristicas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL
);
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Relacionamento entre Tabelas Salas e Características
-- ---------------------------------------------------------------------------

CREATE TABLE sala_caracteristicas (
    sala_id INTEGER NOT NULL,
    caracteristicas_id INTEGER NOT NULL,
    PRIMARY KEY (sala_id, caracteristicas_id),
    FOREIGN KEY (sala_id)
        REFERENCES salas(id),
    FOREIGN KEY (caracteristicas_id)
        REFERENCES caracteristicas(id)
);
-- ---------------------------------------------------------------------------

-- Tabela Notebooks

CREATE TABLE notebooks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR(30) NOT NULL,
    status_defeito BOOLEAN NOT NULL DEFAULT FALSE,
    defeito TEXT,
    disponibilidade BOOLEAN NOT NULL DEFAULT TRUE
);
-- ---------------------------------------------------------------------------

-- Tabela Carrinhos 

CREATE TABLE carrinhos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    disponibilidade BOOLEAN NOT NULL DEFAULT TRUE
);
-- ---------------------------------------------------------------------------

-- Tabela de Reservas

CREATE TABLE reservas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    sala_id INTEGER,
    notebooks_id INTEGER,
    carrinho_id INTEGER,
    data_inicio TIMESTAMP NOT NULL,
    data_fim TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'aguardando',
    categoria VARCHAR(60),
    item VARCHAR(100),
    professor VARCHAR(60),
    curso VARCHAR(100),
    motivo TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id),
    FOREIGN KEY (sala_id)
        REFERENCES salas(id),
    FOREIGN KEY (notebooks_id)
        REFERENCES notebooks(id),
    FOREIGN KEY (carrinho_id)
        REFERENCES carrinhos(id)
);
-- ---------------------------------------------------------------------------
-- Migração: colunas que a API de reservas utiliza.
-- Rode este bloco apenas se a tabela "reservas" já existir
-- em um banco que ainda não tenha estas colunas.
-- ---------------------------------------------------------------------------

ALTER TABLE reservas
    ADD COLUMN IF NOT EXISTS categoria VARCHAR(60),
    ADD COLUMN IF NOT EXISTS item VARCHAR(100),
    ADD COLUMN IF NOT EXISTS professor VARCHAR(60),
    ADD COLUMN IF NOT EXISTS curso VARCHAR(100),
    ADD COLUMN IF NOT EXISTS motivo TEXT,
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
-- ---------------------------------------------------------------------------
